# Generated by Django 3.2 on 2021-04-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_proname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ProImg',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='صورة المنتج'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProName',
            field=models.CharField(max_length=150, verbose_name='اسم المنتج كامل'),
        ),
    ]
