# Generated by Django 3.2 on 2021-04-24 14:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210424_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ProDesc',
            field=ckeditor.fields.RichTextField(verbose_name='تفاصيل المنتج'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProPrice',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='السعر'),
        ),
    ]
