# Generated by Django 3.2 on 2021-04-30 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ProCtegory',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='نوع المنتج'),
            preserve_default=False,
        ),
    ]
