# Generated by Django 3.2 on 2021-05-01 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_proctegory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ProCtegory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='نوع المنتج'),
        ),
    ]
