# Generated by Django 3.2 on 2021-05-01 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
        ('product', '0007_alter_product_proctegory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ProBrand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Brands', to='brands.brand', verbose_name='الماركة'),
        ),
    ]
