# Generated by Django 3.2 on 2021-05-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_product_proimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ProImg',
            new_name='ProImg_2',
        ),
        migrations.AddField(
            model_name='product',
            name='ProImg_1',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='صورة المنتج1 '),
        ),
    ]
