# Generated by Django 3.2 on 2021-05-04 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_product_proslug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ProSlug',
            field=models.SlugField(blank=True, null=True, verbose_name='URl'),
        ),
    ]
