# Generated by Django 3.2 on 2021-05-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_product_proslug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ProSlug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True, verbose_name='URl'),
        ),
    ]
