# Generated by Django 3.2 on 2021-05-07 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_product_proslug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ProSlug',
            new_name='slug',
        ),
    ]
