# Generated by Django 3.2 on 2021-05-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ProPrice',
            field=models.DecimalField(decimal_places=0, max_digits=6, verbose_name='السعر'),
        ),
    ]
