# Generated by Django 3.2 on 2021-05-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_product_proprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ProImg_1',
            field=models.ImageField(blank=True, default='static/assets/images/no-image.jpg', null=True, upload_to='img/', verbose_name='صورة المنتج1 '),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProImg_2',
            field=models.ImageField(blank=True, default='static/assets/images/no-image.jpg', null=True, upload_to='img/', verbose_name='صورة المنتج2 '),
        ),
    ]
