# Generated by Django 3.2 on 2021-05-13 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0021_auto_20210507_1640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productalternative',
            options={'verbose_name': 'ProductAlternative', 'verbose_name_plural': 'ProductAlternatives'},
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='product.product')),
            ],
            options={
                'verbose_name': 'OrderItem',
                'verbose_name_plural': 'OrderItems',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrdStartDate', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ اضافة المنتج')),
                ('OrdOrderedDate', models.DateTimeField()),
                ('OrdOrdered', models.BooleanField(default=False)),
                ('OrdItem', models.ManyToManyField(to='product.Product', verbose_name='المنتجات المطلوبة')),
                ('OrdName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='أسم المستخدم')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
