# Generated by Django 3.2 on 2021-05-13 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_orderitem_proquantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='ProQuantity',
            new_name='quantity',
        ),
    ]
