# Generated by Django 3.2 on 2021-05-15 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='OrdItem',
            new_name='items',
        ),
    ]
