# Generated by Django 3.2 on 2021-05-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_rename_orditem_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='product.OrderItem', verbose_name='المنتجات المطلوبة'),
        ),
    ]
