# Generated by Django 3.2 on 2021-05-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_alter_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ProDiscountPrice',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True, verbose_name='سعر السوق'),
        ),
    ]
