# Generated by Django 3.2 on 2021-05-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_alter_product_prodiscountprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ProDiscountPrice',
            field=models.FloatField(blank=True, null=True, verbose_name='سعر السوق'),
        ),
    ]
