# Generated by Django 3.2 on 2021-05-21 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_alter_product_prodiscountprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='OrdName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.customer', verbose_name='أسم المستخدم'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.customer', verbose_name='أسم المستخدم'),
        ),
        migrations.DeleteModel(
            name='ProductAlternative',
        ),
    ]
