# Generated by Django 3.2 on 2021-05-21 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_auto_20210521_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='OrdName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.customer', verbose_name='أسم المستخدم'),
        ),
    ]
